; BLDC Controller STM32 — PlatformIO
; Płytka: WeAct Black Pill (STM32F411CEU6)
; Programator: USB DFU

[env:blackpill_f411ce]
platform    = ststm32
board       = blackpill_f411ce
framework   = cmsis
build_flags = 
    -DSTM32F411xE
    -I include
    -I src
    -lm
    -Wl,-u,_printf_float
    -DUSB_CDC_ENABLED

; Programowanie przez USB DFU
debug_tool  = stlink
